const mongoose = require("mongoose");
const Data = require("../model/dataModel");

let cloudinary = require("cloudinary").v2;

exports.createData = async (req, res) => {
  try {
    // console.log("Received files:", req.files);
    // console.log("Body:", req.body);
    const { title, description, price } = req.body;

    let titleUnique = await Data.findOne({ title });

    if (titleUnique) {
      return res.send({
        status: false,
        message: "Product already exists",
      });
    }

    if (!title || !description || !price) {
      return res.status(400).json({
        success: false,
        message: "All fields are required",
      });
    }

    // console.log(req.files);
    // handle images uploaded by Multer (Cloudinary)
    const imageUrls = req.files
      ? req.files.map((file) => ({
          url: file.path,
          public_id: file.filename,
          originalName: file.originalname,
        }))
      : [];

    let newData = new Data({ title, description, price, images: imageUrls }); // creating new instance of data 
    await newData.save(); // save in mongodb

    res.send({
      status: true,
      message: "Product added successfully",
      data: newData,
    });
  } catch (error) {
    console.error("Error creating data:", error);
    res.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
};

exports.getAllData = async (req, res) => {
  try {
    let allData = await Data.find();

    if (allData.length === 0) {
      return res.status(200).json({
        success: true,
        message: "No data to show",
        count: 0,
        data: [],
      });
    }
    res.status(200).json({
      success: true,
      count: allData.length,
      data: allData,
    });
  } catch (error) {
    console.error("Error fetching data:", error);
    res.status(500).json({
      success: false,
      message: "Internal Server Error",
    });
  }
};

//deletes the whole data including the image both from mongodb and cloudinary
exports.DeleteData = async (req, res) => {
  const { id } = req.params;

  // 1. Validate ObjectId
  if (!mongoose.Types.ObjectId.isValid(id)) {
    return res.status(400).json({
      status: false,
      message: "Invalid product ID",
    });
  }
  const product = await Data.findById(id);
  // to get the product images id but we cannot access it to delete the images from cloudinary
  // as th id is generated by mongodb and cloudinary doesn't know any thing about it
  // product.images.forEach((img, index) => {
  //   console.log(`image id of index ${index} is ${img._id}`);
  // });

  // 2. Find product
  if (!product) {
    return res.status(404).json({
      status: false,
      message: "Product not found",
    });
  }

  // as image array of object we use the loop here and specifically (for let ) instead of (map)
  // because map run without waiting for data to be deleted whole (for let) is safer and another 
  // operation runs only when deletion is completed for 1st, 2nd and so on
  if (product.images && product.images.length > 0) {
    for (let img of product.images) {
      await cloudinary.uploader.destroy(img.public_id);
    }
  }

  // 4. Delete product from MongoDB
  await Data.findByIdAndDelete(id);

  // 5. Send success response
  return res.status(200).json({
    status: true,
    message: "Product and all related images deleted successfully",
  });
};

//delete only the image from cloudinary and mongodb keeping other data safe
exports.DeleteImage = async (req, res) => {
  let public_id = req.query.public_id; //get the public id from the query
  let { id } = req.params; //get the id

  if (!public_id) {
    return res.status(400).json({
      status: false,
      message: "public id not found",
    });
  }

  if (!mongoose.Types.ObjectId.isValid(id)) {
    return res.status(400).json({
      status: false,
      message: "Invalid product ID",
    });
  }

  let product = await Data.findById(id);
  // console.log(`product id is ${id} and public id is ${public_id}`);
  if (!product) {
    return res.status(404).json({
      status: false,
      message: "product not found",
    });
  }

  // as the image is array of object we use this find method and compare the public_id stored in cloudinary and mongodb
  let image = product.images.find((img) => img.public_id === public_id);

  if (!image) {
    return res.status(404).json({
      status: false,
      message: "image not found",
    });
  }

  // Delete image from Cloudinary
  await cloudinary.uploader.destroy(public_id);

  // Remove image from MongoDB
  const updatedProduct = await Data.findByIdAndUpdate(
    id,
    { $pull: { images: { public_id } } },
    { new: true }
  );

  res.status(200).json({
    status: true,
    message: "Image deleted successfully",
    data: updatedProduct,
  });
}